apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gq0ynk6ux-go 
  janus-idp.io/tekton: gq0ynk6ux-go
  backstage.io/kubernetes-id: gq0ynk6ux-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gq0ynk6ux-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml