apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gq0ynk6ux-go-gitops
  description: This is GitOps manifest for gq0ynk6ux-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=gq0ynk6ux-go
    backstage.io/kubernetes-id: gq0ynk6ux-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: gq0ynk6ux-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gq0ynk6ux-go
